version: '3'
x-config:
  environment: &environment
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - PGUSER=postgres
    - PGHOST=postgres
    - PGDATABASE=postgres
    - PGPASSWORD=mysecretpassword
    - PGPORT=5432

services:

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  redis:
    image: 'redis:latest'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: *environment
    depends_on:
      - postgres
      - redis
      - worker

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment: *environment
    depends_on:
      - redis

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
    restart: always
    depends_on:
      - client
      - api
